### PR TITLE
FP256BN from https://github.com/miracl/core

### PR DESCRIPTION
**Pull request by ale-linux**

### CODE REVIEW

**Review by mastersingh24 — CHANGES_REQUESTED** [review]
@ale-linux  -  I assume you want to use miracl/core for new code  moving forward?  As I recall, we could not easily replace the use of fabric-amcl/amcl in Fabric with miracl/core.

Also, these files needs to be generated from https://github.com/miracl/core/tree/master/go.  We use https://github.com/hyperledger/fabric-amcl/blob/main/createpkg.sh to create the "old" amcl folder.  Can you do something similar to generate core as well?

**Comment by ale-linux** [comment]
hey @mastersingh24 - yeah, miracl/amcl seems to be abandoned (and it has issues such as races and more). We need to keep the old version for backward compatibility since the two implementations are not immediately compatible (e.g. different byte representation of elements). 

Yes, the new code was obtained similarly by running the script and sedding imports

**Comment by ale-linux** [comment]
(I'm force pushing some stuff - I'll mark it as WIP not to waste your time and unmark when ready for review, but it's good to get your comments already ofc).

**Comment by mastersingh24** [comment]
> (I'm force pushing some stuff - I'll mark it as WIP not to waste your time and unmark when ready for review, but it's good to get your comments already ofc).

Sounds good!

**Comment by ale-linux** [comment]
okkkk I think I'm ready to go - how would you handle the "old" script (used to generate the `amcl` directory) and the "new" script (used to generate the `core` directory)? Both directories will need to coexist for a while till we transition away from the miracl/amcl so I guess we want to keep both scripts. Wdyt?

**Comment by mastersingh24** [comment]
> okkkk I think I'm ready to go - how would you handle the "old" script (used to generate the `amcl` directory) and the "new" script (used to generate the `core` directory)? Both directories will need to coexist for a while till we transition away from the miracl/amcl so I guess we want to keep both scripts. Wdyt?

Yeah - we can probably keep both scripts for now.  Maybe we should consider eventually deleting amcl and that script from main at some point.  We do vendor fabric-amcl in Fabric, so we'd probably be ok.  But let's leave that for another day!

**Comment by ale-linux** [comment]
OK @mastersingh24 - I've got both scripts, the generated sources and an updated `README.md`. Do we dare? :grin:

**Comment by mastersingh24** [comment]
> OK @mastersingh24 - I've got both scripts, the generated sources and an updated `README.md`. Do we dare? 😁

I think so!

**Review by mastersingh24 — APPROVED** [review]

**Pull request merged**
