### PR TITLE
Change maintainer file to a pointer

### PR DESCRIPTION
**Pull request by ryjones**
The TOC approved a requirement that maintainers
that have not been active in over three to six
months be move to emeritus status.

These maintainers have not been active in over
one year.

hyperledger/toc#32

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by C0rWin** [comment]
In general, this repo has been without significant activity for quite a while now.

**Review by mbwhite — DISMISSED** [review]

**Comment by denyeart** [comment]
I'll shift this one to reference the core Fabric maintainers...

**Comment by ryjones** [comment]
@denyeart 
Should this repo be archived instead?

**Comment by denyeart** [comment]
> @denyeart Should this repo be archived instead?

No, core fabric still pulls in fabric-amcl, so I'll switch it to reference the fabric repo maintainers.

**Comment by ryjones** [comment]
@denyeart like this?

**Review by denyeart — APPROVED** [review]
Perfect, thanks Ry!

**Pull request merged**
